import { pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core'

const timestamps = {
  created_at: timestamp('created_at').defaultNow().notNull(),
  updated_at: timestamp('updated_at').defaultNow().notNull()
}

// Δήλωση Βαπτίσεως
export const baptismDeclarations = pgTable('baptism_declarations', {
  id: serial('id').primaryKey(),
  iera_mitropolis: text('iera_mitropolis'),
  ieros_naos: text('ieros_naos'),
  arithmos_protokolou: text('arithmos_protokolou'),
  efimerios: text('efimerios'),
  efimerios_naou: text('efimerios_naou'),
  baptism_imera: text('baptism_imera'),
  baptism_minas: text('baptism_minas'),
  baptism_etos: text('baptism_etos'),
  baptism_imera_evdomadas: text('baptism_imera_evdomadas'),
  baptism_naos: text('baptism_naos'),
  pateras_onoma: text('pateras_onoma'),
  mitera_eponymo_genous: text('mitera_eponymo_genous'),
  mitera_onoma: text('mitera_onoma'),
  katoikia: text('katoikia'),
  odos: text('odos'),
  arithmos_odou: text('arithmos_odou'),
  gennitiki_imera: text('gennitiki_imera'),
  gennitiki_poli: text('gennitiki_poli'),
  lixiarxeio_praxis_arithmos: text('lixiarxeio_praxis_arithmos'),
  lixiarxeio_tomos: text('lixiarxeio_tomos'),
  lixiarxeio_etos: text('lixiarxeio_etos'),
  lixiarchos: text('lixiarchos'),
  onoma_baptisthen: text('onoma_baptisthen'),
  anadexamenos: text('anadexamenos'),
  anadexamenos_katoikia: text('anadexamenos_katoikia'),
  anadexamenos_odos: text('anadexamenos_odos'),
  anadexamenos_arithmos: text('anadexamenos_arithmos'),
  efimerios_ypografi: text('efimerios_ypografi'),
  pateras_ypografi: text('pateras_ypografi'),
  mitera_ypografi: text('mitera_ypografi'),
  anadoxos_ypografi: text('anadoxos_ypografi'),
  ...timestamps
})

// Προσδιορισμός Βαπτίσεως
export const baptismSpecifications = pgTable('baptism_specifications', {
  id: serial('id').primaryKey(),
  iera_mitropolis: text('iera_mitropolis'),
  ieros_naos: text('ieros_naos'),
  arithmos_protokolou: text('arithmos_protokolou'),
  simeron_imera: text('simeron_imera'),
  simeron_minas: text('simeron_minas'),
  simeron_etos: text('simeron_etos'),
  goneis_1: text('goneis_1'),
  goneis_1_id_arithmos: text('goneis_1_id_arithmos'),
  goneis_1_id_ekdosi: text('goneis_1_id_ekdosi'),
  goneis_2: text('goneis_2'),
  goneis_2_id_arithmos: text('goneis_2_id_arithmos'),
  goneis_2_id_ekdosi: text('goneis_2_id_ekdosi'),
  teknon_gennitiki_imera: text('teknon_gennitiki_imera'),
  teknon_gennitiki_minas: text('teknon_gennitiki_minas'),
  teknon_gennitiki_etos: text('teknon_gennitiki_etos'),
  teknon_nosokomeio: text('teknon_nosokomeio'),
  teknon_nosokomeio_etos: text('teknon_nosokomeio_etos'),
  lixiarxeio_praxis_arithmos: text('lixiarxeio_praxis_arithmos'),
  lixiarxeio_tomos: text('lixiarxeio_tomos'),
  lixiarxeio_etos: text('lixiarxeio_etos'),
  teknon_onoma: text('teknon_onoma'),
  baptisma_minas: text('baptisma_minas'),
  katoikia_odos: text('katoikia_odos'),
  baptisma_imera: text('baptisma_imera'),
  baptisma_etos: text('baptisma_etos'),
  anadoxos: text('anadoxos'),
  anadoxos_gamochronologia: text('anadoxos_gamochronologia'),
  anadoxos_gamonaos: text('anadoxos_gamonaos'),
  topos_ypovrolis: text('topos_ypovrolis'),
  imera_ypovrolis: text('imera_ypovrolis'),
  etos_ypovrolis: text('etos_ypovrolis'),
  ...timestamps
})

// Δήλωση Γάμου
export const marriageDeclarations = pgTable('marriage_declarations', {
  id: serial('id').primaryKey(),
  iera_mitropoli: text('iera_mitropoli'),
  arithmos_lixiarkis_praxis: text('arithmos_lixiarkis_praxis'),
  tomos: text('tomos'),
  etos: text('etos'),
  ieros_naos: text('ieros_naos'),
  dimotiko_topiko: text('dimotiko_topiko'),
  dimos_dimotiki_enotita: text('dimos_dimotiki_enotita'),
  nomos: text('nomos'),
  arithmos_vivliou: text('arithmos_vivliou'),
  iereus: text('iereus'),
  iereus_eniporias: text('iereus_eniporias'),
  gamos_imera: text('gamos_imera'),
  gamos_minas: text('gamos_minas'),
  gamos_etos: text('gamos_etos'),
  gamos_ora: text('gamos_ora'),
  dogma: text('dogma'),
  dogma_tagseis: text('dogma_tagseis'),
  // Στοιχεία Συζύγου
  syzygos_eponymo: text('syzygos_eponymo'),
  syzygou_eponymo: text('syzygou_eponymo'),
  syzygos_onoma: text('syzygos_onoma'),
  syzygou_onoma: text('syzygou_onoma'),
  syzygos_epaggelma: text('syzygos_epaggelma'),
  syzygou_epaggelma: text('syzygou_epaggelma'),
  syzygos_thriskevma: text('syzygos_thriskevma'),
  syzygou_thriskevma: text('syzygou_thriskevma'),
  syzygos_ithagenia: text('syzygos_ithagenia'),
  syzygou_ithagenia: text('syzygou_ithagenia'),
  syzygos_afm: text('syzygos_afm'),
  syzygou_afm: text('syzygou_afm'),
  syzygos_amka: text('syzygos_amka'),
  syzygou_amka: text('syzygou_amka'),
  syzygos_foreas_asfalisys: text('syzygos_foreas_asfalisys'),
  syzygou_foreas_asfalisys: text('syzygou_foreas_asfalisys'),
  syzygos_topos_gennisis: text('syzygos_topos_gennisis'),
  syzygou_topos_gennisis: text('syzygou_topos_gennisis'),
  syzygos_nomos_gennisis: text('syzygos_nomos_gennisis'),
  syzygou_nomos_gennisis: text('syzygou_nomos_gennisis'),
  syzygos_dimos_gennisis: text('syzygos_dimos_gennisis'),
  syzygou_dimos_gennisis: text('syzygou_dimos_gennisis'),
  syzygos_dimotiki_gennisis: text('syzygos_dimotiki_gennisis'),
  syzygou_dimotiki_gennisis: text('syzygou_dimotiki_gennisis'),
  syzygos_chora_gennisis: text('syzygos_chora_gennisis'),
  syzygou_chora_gennisis: text('syzygou_chora_gennisis'),
  syzygos_chronologia_gennisis: text('syzygos_chronologia_gennisis'),
  syzygou_chronologia_gennisis: text('syzygou_chronologia_gennisis'),
  syzygos_katikia_nomos: text('syzygos_katikia_nomos'),
  syzygou_katikia_nomos: text('syzygou_katikia_nomos'),
  syzygos_katikia_dimos: text('syzygos_katikia_dimos'),
  syzygou_katikia_dimos: text('syzygou_katikia_dimos'),
  syzygos_katikia_dimotiki: text('syzygos_katikia_dimotiki'),
  syzygou_katikia_dimotiki: text('syzygou_katikia_dimotiki'),
  syzygos_katikia_chora: text('syzygos_katikia_chora'),
  syzygou_katikia_chora: text('syzygou_katikia_chora'),
  syzygos_dimotis_dimos: text('syzygos_dimotis_dimos'),
  syzygou_dimotis_dimos: text('syzygou_dimotis_dimos'),
  syzygos_dimotis_nomos: text('syzygos_dimotis_nomos'),
  syzygou_dimotis_nomos: text('syzygou_dimotis_nomos'),
  syzygos_dimotis_arithmos: text('syzygos_dimotis_arithmos'),
  syzygou_dimotis_arithmos: text('syzygou_dimotis_arithmos'),
  syzygos_pateras: text('syzygos_pateras'),
  syzygou_pateras: text('syzygou_pateras'),
  syzygos_mitera: text('syzygos_mitera'),
  syzygou_mitera: text('syzygou_mitera'),
  zeygos_katikia: text('zeygos_katikia'),
  zeygos_katikia_2: text('zeygos_katikia_2'),
  zeygos_nomos: text('zeygos_nomos'),
  zeygos_nomos_2: text('zeygos_nomos_2'),
  zeygos_dimos: text('zeygos_dimos'),
  zeygos_dimos_2: text('zeygos_dimos_2'),
  zeygos_dimotiki: text('zeygos_dimotiki'),
  zeygos_dimotiki_2: text('zeygos_dimotiki_2'),
  zeygos_topiki: text('zeygos_topiki'),
  zeygos_topiki_2: text('zeygos_topiki_2'),
  zeygos_chora: text('zeygos_chora'),
  zeygos_chora_2: text('zeygos_chora_2'),
  eponymo_teknon: text('eponymo_teknon'),
  eponymo_teknon_2: text('eponymo_teknon_2'),
  syzygos_oik_katastasi: text('syzygos_oik_katastasi'),
  syzygou_oik_katastasi: text('syzygou_oik_katastasi'),
  syzygos_vathmos_gamou: text('syzygos_vathmos_gamou'),
  syzygou_vathmos_gamou: text('syzygou_vathmos_gamou'),
  syzygos_ekpaideusi: text('syzygos_ekpaideusi'),
  syzygou_ekpaideusi: text('syzygou_ekpaideusi'),
  syzygos_arithmos_adeia_gamou: text('syzygos_arithmos_adeia_gamou'),
  syzygos_ieras_mitropoli_adeia: text('syzygos_ieras_mitropoli_adeia'),
  syzygou_arithmos_adeia_gamou: text('syzygou_arithmos_adeia_gamou'),
  syzygou_ieras_mitropoli_adeia: text('syzygou_ieras_mitropoli_adeia'),
  syzygos_arithmos_paravolo: text('syzygos_arithmos_paravolo'),
  syzygou_arithmos_paravolo: text('syzygou_arithmos_paravolo'),
  ...timestamps
})

// Πιστοποιητικό Αγαμίας Τύπος Α
export const certificatesA = pgTable('certificates_a', {
  id: serial('id').primaryKey(),
  iera_mitropolis: text('iera_mitropolis'),
  ieros_naos: text('ieros_naos'),
  arithmos_protokolou: text('arithmos_protokolou'),
  efimerios: text('efimerios'),
  efimerios_naou: text('efimerios_naou'),
  agamos_onoma: text('agamos_onoma'),
  patros: text('patros'),
  mitros: text('mitros'),
  gennitikos_topos: text('gennitikos_topos'),
  gennitiki_imera: text('gennitiki_imera'),
  gennitiki_poli: text('gennitiki_poli'),
  etos_genniseos: text('etos_genniseos'),
  katoikia_apo: text('katoikia_apo'),
  katoikia_etos: text('katoikia_etos'),
  odos: text('odos'),
  arithmos_odou: text('arithmos_odou'),
  ilikia: text('ilikia'),
  epaggelma: text('epaggelma'),
  christianos: text('christianos'),
  agamos_kata: text('agamos_kata'),
  dynatos_gamos: text('dynatos_gamos'),
  ekdosi_adeia: text('ekdosi_adeia'),
  topos_ekdosis: text('topos_ekdosis'),
  imera_ekdosis: text('imera_ekdosis'),
  etos_ekdosis: text('etos_ekdosis'),
  ...timestamps
})

// Πιστοποιητικό Αγαμίας Τύπος Β
export const certificatesB = pgTable('certificates_b', {
  id: serial('id').primaryKey(),
  iera_mitropolis: text('iera_mitropolis'),
  ieros_naos: text('ieros_naos'),
  arithmos_protokolou: text('arithmos_protokolou'),
  efimerios: text('efimerios'),
  efimerios_naou: text('efimerios_naou'),
  proselthen: text('proselthen'),
  agamos_onoma: text('agamos_onoma'),
  patros: text('patros'),
  mitros: text('mitros'),
  gennitikos_topos: text('gennitikos_topos'),
  gennitiki_imera: text('gennitiki_imera'),
  gennitiki_poli: text('gennitiki_poli'),
  etos_genniseos: text('etos_genniseos'),
  katoikia_apo: text('katoikia_apo'),
  katoikia_etos: text('katoikia_etos'),
  odos: text('odos'),
  arithmos_odou: text('arithmos_odou'),
  ilikia: text('ilikia'),
  epaggelma: text('epaggelma'),
  christianos: text('christianos'),
  dilosi_imera: text('dilosi_imera'),
  martyras_1: text('martyras_1'),
  martyras_1_id: text('martyras_1_id'),
  martyras_1_astynomia: text('martyras_1_astynomia'),
  martyras_2: text('martyras_2'),
  martyras_2_id: text('martyras_2_id'),
  martyras_2_astynomia: text('martyras_2_astynomia'),
  dilosi_katoikia: text('dilosi_katoikia'),
  dilosi_enthen: text('dilosi_enthen'),
  dilosi_odos: text('dilosi_odos'),
  agamos_kata: text('agamos_kata'),
  dynatos_gamos: text('dynatos_gamos'),
  ekdosi_adeia: text('ekdosi_adeia'),
  martyras_ypografi_1: text('martyras_ypografi_1'),
  martyras_ypografi_2: text('martyras_ypografi_2'),
  ekdosi_adeia_2: text('ekdosi_adeia_2'),
  topos_ekdosis: text('topos_ekdosis'),
  imera_ekdosis: text('imera_ekdosis'),
  etos_ekdosis: text('etos_ekdosis'),
  ...timestamps
})
